trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '656673e5-8d01-434d-b2f8-30ce7b1d8a24'
  imageRepository: 'jdemehw'
  containerRegistry: 'examplesolcontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  terraformVersion: '1.5.7'
  acr_username: '$(acr_username)'
  acr_password: '$(acr_password)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default    # <-- Використовує твій локальний агент!
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: TerraformPlan
  displayName: "Terraform Plan"
  dependsOn: Build
  condition: |
      or(
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
  jobs:
  - job: TerraformPlan
    displayName: "Terraform Plan"
    pool:
      name: Default   # <-- Теж локальний агент
    steps:
    - checkout: self

    - script: |
        echo "Installing Terraform..."
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform -y
      displayName: 'Install Terraform'

    - script: |
        terraform -version
        cd terraform
        terraform init -reconfigure
        terraform plan \
          -var="acr_username=$(acr_username)" \
          -var="acr_password=$(acr_password)"
      displayName: 'Terraform Init & Plan'

- stage: TerraformApply
  displayName: "Terraform Apply"
  dependsOn: TerraformPlan
  condition: |
    and(
      succeeded('TerraformPlan'),
      eq(variables['Build.SourceBranch'], 'refs/heads/main')
    )
  jobs:
  - job: TerraformApply
    displayName: "Terraform Apply"
    pool:
      name: Default   # <-- Локальний агент
    steps:
    - checkout: self

    - script: |
        echo "Installing Terraform..."
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform -y
      displayName: 'Install Terraform'

    - script: |
        terraform -version
        cd terraform
        terraform init -reconfigure
        terraform apply -auto-approve \
          -var="acr_username=$(acr_username)" \
          -var="acr_password=$(acr_password)"
      displayName: 'Terraform Init & Apply'
