apiVersion: v1
kind: Service
metadata:
  name: bestrong-webapp-service
  labels:
    app: webapp
    tier: backend
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
