apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestrong-webapp-deployment
  labels:
    app: bestrong-webapp-deployment
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        tier: backend 
    spec:
      containers:
      - name: bestrong
        image: bestrong
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80